create table "public"."code_highlight" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "code_issue_id" bigint not null,
    "repo_id" bigint not null,
    "filepath" text not null,
    "start_line" bigint not null,
    "end_line" bigint not null
);


alter table "public"."code_highlight" enable row level security;

create table "public"."code_issue" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "repo_id" bigint not null,
    "name" text not null,
    "problem" text not null,
    "solution" text not null
);


alter table "public"."code_issue" enable row level security;

create table "public"."repo" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "name" text not null,
    "owner" text not null,
    "user_id" bigint not null,
    "status" text not null
);


alter table "public"."repo" enable row level security;

alter table "public"."user" add column "email" text not null;

CREATE UNIQUE INDEX code_highlight_pkey ON public.code_highlight USING btree (id);

CREATE UNIQUE INDEX code_issue_pkey ON public.code_issue USING btree (id);

CREATE UNIQUE INDEX repo_pkey ON public.repo USING btree (id);

alter table "public"."code_highlight" add constraint "code_highlight_pkey" PRIMARY KEY using index "code_highlight_pkey";

alter table "public"."code_issue" add constraint "code_issue_pkey" PRIMARY KEY using index "code_issue_pkey";

alter table "public"."repo" add constraint "repo_pkey" PRIMARY KEY using index "repo_pkey";

alter table "public"."code_highlight" add constraint "code_highlight_code_issue_id_fkey" FOREIGN KEY (code_issue_id) REFERENCES code_issue(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."code_highlight" validate constraint "code_highlight_code_issue_id_fkey";

alter table "public"."code_highlight" add constraint "code_highlight_repo_id_fkey" FOREIGN KEY (repo_id) REFERENCES repo(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."code_highlight" validate constraint "code_highlight_repo_id_fkey";

alter table "public"."code_issue" add constraint "code_issue_repo_id_fkey" FOREIGN KEY (repo_id) REFERENCES repo(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."code_issue" validate constraint "code_issue_repo_id_fkey";

alter table "public"."repo" add constraint "repo_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."repo" validate constraint "repo_user_id_fkey";

grant delete on table "public"."code_highlight" to "anon";

grant insert on table "public"."code_highlight" to "anon";

grant references on table "public"."code_highlight" to "anon";

grant select on table "public"."code_highlight" to "anon";

grant trigger on table "public"."code_highlight" to "anon";

grant truncate on table "public"."code_highlight" to "anon";

grant update on table "public"."code_highlight" to "anon";

grant delete on table "public"."code_highlight" to "authenticated";

grant insert on table "public"."code_highlight" to "authenticated";

grant references on table "public"."code_highlight" to "authenticated";

grant select on table "public"."code_highlight" to "authenticated";

grant trigger on table "public"."code_highlight" to "authenticated";

grant truncate on table "public"."code_highlight" to "authenticated";

grant update on table "public"."code_highlight" to "authenticated";

grant delete on table "public"."code_highlight" to "service_role";

grant insert on table "public"."code_highlight" to "service_role";

grant references on table "public"."code_highlight" to "service_role";

grant select on table "public"."code_highlight" to "service_role";

grant trigger on table "public"."code_highlight" to "service_role";

grant truncate on table "public"."code_highlight" to "service_role";

grant update on table "public"."code_highlight" to "service_role";

grant delete on table "public"."code_issue" to "anon";

grant insert on table "public"."code_issue" to "anon";

grant references on table "public"."code_issue" to "anon";

grant select on table "public"."code_issue" to "anon";

grant trigger on table "public"."code_issue" to "anon";

grant truncate on table "public"."code_issue" to "anon";

grant update on table "public"."code_issue" to "anon";

grant delete on table "public"."code_issue" to "authenticated";

grant insert on table "public"."code_issue" to "authenticated";

grant references on table "public"."code_issue" to "authenticated";

grant select on table "public"."code_issue" to "authenticated";

grant trigger on table "public"."code_issue" to "authenticated";

grant truncate on table "public"."code_issue" to "authenticated";

grant update on table "public"."code_issue" to "authenticated";

grant delete on table "public"."code_issue" to "service_role";

grant insert on table "public"."code_issue" to "service_role";

grant references on table "public"."code_issue" to "service_role";

grant select on table "public"."code_issue" to "service_role";

grant trigger on table "public"."code_issue" to "service_role";

grant truncate on table "public"."code_issue" to "service_role";

grant update on table "public"."code_issue" to "service_role";

grant delete on table "public"."repo" to "anon";

grant insert on table "public"."repo" to "anon";

grant references on table "public"."repo" to "anon";

grant select on table "public"."repo" to "anon";

grant trigger on table "public"."repo" to "anon";

grant truncate on table "public"."repo" to "anon";

grant update on table "public"."repo" to "anon";

grant delete on table "public"."repo" to "authenticated";

grant insert on table "public"."repo" to "authenticated";

grant references on table "public"."repo" to "authenticated";

grant select on table "public"."repo" to "authenticated";

grant trigger on table "public"."repo" to "authenticated";

grant truncate on table "public"."repo" to "authenticated";

grant update on table "public"."repo" to "authenticated";

grant delete on table "public"."repo" to "service_role";

grant insert on table "public"."repo" to "service_role";

grant references on table "public"."repo" to "service_role";

grant select on table "public"."repo" to "service_role";

grant trigger on table "public"."repo" to "service_role";

grant truncate on table "public"."repo" to "service_role";

grant update on table "public"."repo" to "service_role";


